### PR TITLE
fix(envs): add __getattr__ to _LazyAsyncVectorEnv for attribute proxying

### PR DESCRIPTION
**Pull request by reeceomahoney**
## Type / Scope

- **Type**: Bug
- **Scope**: envs

## Summary / Motivation

`_LazyAsyncVectorEnv` (introduced in #3274) only explicitly delegates `reset`, `step`, `call`, and `get_attr`. Accessing any other attribute on the wrapper — such as `env.unwrapped.metadata["render_fps"]` in `eval_policy` — raises `AttributeError`:

```
  File "/home/reece/Work/lerobot/src/lerobot/scripts/lerobot_eval.py", line 422, in eval_policy
    env.unwrapped.metadata["render_fps"],
    ^^^^^^^^^^^^^
AttributeError: '_LazyAsyncVectorEnv' object has no attribute 'unwrapped'
```

This is hit whenever eval runs with video rendering enabled (`max_episodes_rendered > 0`).

## Related issues

- Related: #3274

## What changed

- Added `__getattr__` to `_LazyAsyncVectorEnv` that materializes the underlying `AsyncVectorEnv` and forwards the attribute lookup. This is the standard proxy pattern and ensures all attributes (e.g. `unwrapped`, `metadata`, `spec`) work transparently.

## How was this tested

- Ran `pre-commit run --files src/lerobot/envs/utils.py` — all checks pass.
- Reproduced the error by running `lerobot-eval` with video rendering enabled; confirmed it no longer raises `AttributeError`.

## Checklist (required before merge)

- [x] Linting/formatting run (`pre-commit run -a`)
- [x] All tests pass locally (`pytest`)
- [ ] Documentation updated
- [ ] CI is green

## Reviewer notes

- Single 4-line change in `src/lerobot/envs/utils.py`.
- `__getattr__` is only called when normal attribute lookup fails, so the existing explicit methods (`reset`, `step`, etc.) are unaffected.

### CODE REVIEW

**Review by HaomingSong — COMMENTED** [review]
Thanks for fixing this. I have one concern about using `__getattr__` here.

My understanding is that `_LazyAsyncVectorEnv` is intended to materialize only when a live `AsyncVectorEnv` is actually needed, such as via `reset()`, `step()`, `call()`, or `get_attr()`. With this change, any missing attribute lookup will also call `_ensure()`, which means passive attribute access like `hasattr(env, "metadata")`, `getattr(env, "spec", None)`, or `env.unwrapped` can now instantiate the underlying env. That seems to weaken the lazy-init boundary of the wrapper.

In the `eval_policy` path, `env.unwrapped.metadata["render_fps"]` is read only after `reset()/call()/step()` have already executed, so the underlying env should already be materialized there. Because of that, full attribute proxying looks broader than necessary for the current bug.

Could you take a look at #3416? I use a narrower fix that preserves the lazy-initialization semantics more closely.

**Comment by reeceomahoney** [comment]
Thanks for the fix! Will close this
